version : '3'

services:
  postgresdb:
    image: postgres
    environment:
      - POSTGRES_DB=gostack_gobarber
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=docker
    ports:
        - ${POSTGRES_PORT}:${POSTGRES_PORT}
    networks:
      - gostack_network

  mongodb:
    image: mongo:latest
    ports:
        - 27017:27017
    networks:
      - gostack_network

  redis:
    image: redis:alpine
    ports:
        - 6379:6379
    networks:
      - gostack_network

  api_go_barber:
    depends_on:
      - postgresdb
      - mongodb
      - redis
    build:
      context: .
      dockerfile: Dockerfile
    environment:
        - CHOKIDAR_USEPOLLING=true
    volumes:
      - .:/app/
      - gobarber_node_modules:/app/node_modules
    ports:
      - 3333:3333
    networks:
      - gostack_network
    restart: always


networks:
  gostack_network:

volumes:
  gobarber_node_modules: {}
